tools: Update intelhex, hexmerge.py and nrfutil for Python 3.9
daniel-thompson/wasp-os pull request #120
Opened 2020-12-07 15:27 UTC by Siroj42

There are problems in the intelhex and nrfutil submodules regarding compatibility with Python 3.9. I noticed them after trying to build wasp-os on Fedora 33. Luckily, they are already fixed in the respective repositories, so simply updating the submodules and copying the hexmerge.py from tools/intelhex/scripts did the job.

2020-12-09 19:50 UTC, Izaic commented
Bump...

@daniel-thompson Could we get this merged? This fix is pretty important.

2020-12-10 19:37 UTC, daniel-thompson requested changes
I've had a similar fix on my own tree for a couple of weeks but I was waiting for nrfutil to get updated (so it didn't have to go the trouble of forking it). Glad to see that's OK now.

Other than the version number bump this looks good!

2020-12-10 19:37 UTC, daniel-thompson commented on tools/hexmerge.py
> +VERSION = '2.3.0'
Why bump the version number here?

2020-12-10 19:46 UTC, daniel-thompson commented on tools/hexmerge.py
> +VERSION = '2.3.0'
Actually I realized why... but drop this change anyway! Better to replace tools/hexmerge.py with a symlink so that's what I've just done.

2020-12-11 00:38 UTC, shulltronics commented
Hey guys,

Could anyone outline how to make this fix manually before the pull request is merged? I'm having trouble compiling wasp-os, and I think it's related to this. Thanks!

2020-12-11 01:52 UTC, Izaic commented
> Hey guys,
> 
> Could anyone outline how to make this fix manually before the pull request is merged? I'm having trouble compiling wasp-os, and I think it's related to this. Thanks!

A quickie temporary solution would be to just build wasp-os from the branch of this patch. While it will be older, you can at least explore a bit until the issue is resolved, and then after that you'll be able to try out the new stuff such as the haptic alarm.

2020-12-12 09:17 UTC, daniel-thompson commented
Applied. Thanks.

2020-12-12 09:17 UTC, closed without merging