Added Docker setup to build wasp-os.
daniel-thompson/wasp-os pull request #164
Opened 2021-02-02 23:22 UTC by shuhaowu

This should make it a bit easier for people to contribute. Also fixed the documentations on how to setup on Debian, as certain recommended packages don't exist.

Signed-off-by: Shuhao Wu <shuhao@shuhaowu.com>

2021-02-03 19:08 UTC, daniel-thompson requested changes
Thanks for the PR. Most of the reviiew comments are about the doucmentation but there is on comment about the dockerfile too.

2021-02-03 19:08 UTC, daniel-thompson commented on docs/install.rst
> +    If you want to use the Docker-based setup, it is assumed that you're using
I think this also needs to mention that docker does not support the BLE tools (wasptool, ota-dfu, etc) so not all functionality is available via docker.

2021-02-03 19:08 UTC, daniel-thompson commented on docs/install.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~
Let's drop the actually from this header.

2021-02-04 00:43 UTC, shuhaowu commented on docs/install.rst
> +    pip3 install --user cbor pysdl2 pygobject cryptography
I needed cryptography. Without it, things like reloader-mcuboot.zip wouldn't build correctly as something complains about the inability to import `cryptography`.

2021-02-04 01:01 UTC, shuhaowu commented on docker/Dockerfile
> +    pip3 install cbor pysdl2 pygobject cryptography;
This image is based on the Ubuntu official image and therefore we need to install all dependencies either manually. I don't think that we should use a Github image, as that would likely be pretty bloated with unnecessary dependencies and therefore would use extra space when you pull the image down.

2021-02-04 01:07 UTC, shuhaowu commented on docs/install.rst
> +    pip3 install --user cbor pysdl2 pygobject cryptography
Here's the trace

```
Zip created at build-pinetime/bootloader-daflasher.zip
make -C reloader/ BOARD=pinetime
make[1]: Entering directory '/home/user/wasp-os/reloader'
arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -g3 -Os -ffunction-sections -fdata-sections -DNRF52832_XXAA -Ilib/CMSIS/CMSIS/Core/Include -Ilib/nrfx -Ilib/nrfx/drivers/include -Ilib/nrfx/mdk -Ilib/nrfx/hal -Isrc/boards/pinetime -Isrc -Wl,-Map=build-pinetime/reloader.map -Lsrc -Llib/nrfx/mdk -Tnrf52832_xxaa.ld build-pinetime/main.o build-pinetime/blit.o build-pinetime/flash.o build-pinetime/spi.o build-pinetime/spinor.o build-pinetime/st7789.o build-pinetime/wdt.o build-pinetime/nrfx_nvmc.o build-pinetime/gcc_startup_nrf52.o build-pinetime/system_nrf52.o -o build-pinetime/reloader.elf
arm-none-eabi-objcopy -O ihex build-pinetime/reloader.elf build-pinetime/reloader.hex
python3 -m nordicsemi dfu genpkg --dev-type 0x0052 --application build-pinetime/reloader.hex build-pinetime/reloader.zip
Failed to import ecdsa, cannot do signing
Zip created at build-pinetime/reloader.zip
arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -g3 -Os -ffunction-sections -fdata-sections -DNRF52832_XXAA -Ilib/CMSIS/CMSIS/Core/Include -Ilib/nrfx -Ilib/nrfx/drivers/include -Ilib/nrfx/mdk -Ilib/nrfx/hal -Isrc/boards/pinetime -Isrc -Wl,-Map=build-pinetime/reloader.map -Lsrc -Llib/nrfx/mdk -Tnrf52832_xxaa_mcuboot.ld build-pinetime/main.o build-pinetime/blit.o build-pinetime/flash.o build-pinetime/spi.o build-pinetime/spinor.o build-pinetime/st7789.o build-pinetime/wdt.o build-pinetime/nrfx_nvmc.o build-pinetime/gcc_startup_nrf52.o build-pinetime/system_nrf52.o -o build-pinetime/reloader-mcuboot.elf
arm-none-eabi-objcopy -O binary build-pinetime/reloader-mcuboot.elf build-pinetime/reloader-mcuboot.bin.tmp
lib/mcuboot/scripts/imgtool.py create \
	--align 4 --version 1.0.0 \
	--header-size 32 --slot-size 475136 --pad-header build-pinetime/reloader-mcuboot.bin.tmp build-pinetime/reloader-mcuboot.bin
Traceback (most recent call last):
  File "lib/mcuboot/scripts/imgtool.py", line 17, in <module>
    from imgtool import main
  File "/home/user/wasp-os/reloader/lib/mcuboot/scripts/imgtool/main.py", line 21, in <module>
    import imgtool.keys as keys
  File "/home/user/wasp-os/reloader/lib/mcuboot/scripts/imgtool/keys/__init__.py", line 19, in <module>
    from cryptography.hazmat.backends import default_backend
ModuleNotFoundError: No module named 'cryptography'
make[1]: *** [Makefile:56: build-pinetime/reloader-mcuboot.bin] Error 1
make[1]: Leaving directory '/home/user/wasp-os/reloader'
make: *** [Makefile:51: reloader] Error 2
```

After that errors:

```
$ ls -l build-pinetime/
total 632
-rw-r--r-- 1 user user 170609 Feb  4 01:06 bootloader-daflasher.zip
-rw-r--r-- 1 user user 474700 Feb  4 01:06 bootloader.hex

```

2021-02-04 20:52 UTC, daniel-thompson commented on docker/Dockerfile
> +    pip3 install cbor pysdl2 pygobject cryptography;
I didn't mean to suggest we should adopt the github image. Simply that I'd like to docker image to be more closely aligned with the CI flow (e.g. same choices of pip3 versus dpkg) to make it easier to maintain.

2021-02-04 20:54 UTC, daniel-thompson commented on docs/install.rst
> +    pip3 install --user cbor pysdl2 pygobject cryptography
Sorry... got confused between two different issues.

cryptography is only needed for pinetime builds... but its too complicated to spell out the differences in the install docs so it's correct to add it as a prerequisite.

2021-02-20 08:46 UTC, daniel-thompson commented
Merged. Thanks.

2021-02-20 08:46 UTC, closed without merging