Word Clock closes  #179
daniel-thompson/wasp-os pull request #180
Opened 2021-03-05 19:47 UTC by bmsleight

Signed-off-by: Brendan M. Sleight <bms.git@barwap.com>

2021-03-08 18:53 UTC, bmsleight commented
Any more comments ?
Merge or not merge ?

2021-03-09 21:46 UTC, daniel-thompson requested changes
Generally this looks ok, just a few niggles really.

2021-03-09 21:46 UTC, daniel-thompson commented on wasp/apps/word_clock.py
> +"""Digital clock
This looks out of date. It needs to be different from the other existing clocks.

2021-03-09 21:46 UTC, daniel-thompson commented on wasp/apps/word_clock.py
> +        mid = draw.lighten(lo, 1)
Are lo and mid used anywhere?

2021-03-09 21:46 UTC, daniel-thompson commented on wasp/apps/word_clock.py
> +        offset_y=int(((5-lines_of_text/2)*24))
Perhaps change the * 24 to something slightly more spaced (26? 27?) to give a better appearance.

2021-03-09 21:46 UTC, daniel-thompson commented on wasp/apps/word_clock.py
> +                "Nine", "Ten", "Eleven"]
Why it this capitalized. Is it possible to capitalize the first word of the phrase instead?

2021-03-10 20:56 UTC, daniel-thompson commented
Applied. Thanks!

2021-03-10 20:56 UTC, closed without merging