feat: add chime feature to timer app
daniel-thompson/wasp-os pull request #306
Opened 2022-02-24 17:40 UTC by thiswillbeyourgithub

2022-02-24 17:41 UTC, thiswillbeyourgithub commented on wasp/apps/timer.py
> -import time
this import was not needed so I removed it

2022-02-28 21:12 UTC, thiswillbeyourgithub commented
The reason the test is failing is `overflowed by 124 bytes`. This could be maybe solved by the PR that merges disaBLE to the settings?

2022-03-27 09:01 UTC, daniel-thompson requested changes
A patch description explaining what this change does and why would be really useful.

In general what is the purpose of the "Repeat" checkbox? In other words why does the user need to make a decision. Can't we just pick the "best" behaviour all the time?

2022-03-27 09:02 UTC, daniel-thompson commented
> The reason the test is failing is `overflowed by 124 bytes`. This could be maybe solved by the PR that merges disaBLE to the settings?

Let's see what happens when this comes back for re-testing. It's possible replacing Game of Life with the Gallery app will have created some extra space.

2022-03-28 21:44 UTC, fgaz commented
While the chime feature is great, I often like my watch to be as silent as possible. Maybe the chime could be optional?

Or even better, there could be a global setting that has 3 volume options (completely silent, vibration, sound) that applies to _all_ apps (well, the timer and the alarm)

2022-03-28 22:15 UTC, thiswillbeyourgithub commented
> While the chime feature is great, I often like my watch to be as silent as possible. Maybe the chime could be optional?
> 
> Or even better, there could be a global setting that has 3 volume options (completely silent, vibration, sound) that applies to _all_ apps (well, the timer and the alarm)

I don't understand. To me, the goal of the timer app is to be notified that X time has passed. I don't see the point of a silent timer app.

2022-04-04 11:11 UTC, thiswillbeyourgithub commented
I'm thinking of working on a pomodoro timer app, largely based on this fork. Maybe you would prefer having two separate apps and leaving this one as is?

2022-04-23 17:42 UTC, thiswillbeyourgithub commented
In the end I don't think this PR is a good idea, seeing the progress i made in #320

2022-04-23 17:42 UTC, closed without merging