A Snake Game Application
daniel-thompson/wasp-os pull request #75
Opened 2020-10-02 13:55 UTC by tht-jxny

This is to add a Snake Game App to wasp-os.
One can control the snake by swiping in the desired direction. 
Since only the necessary pixels are drawn again every tick, there is the problem that the first time the snake eats the food nothing seems to happen. I'd appreciate it if you could tell me how to fix this flaw.
The application comes with a Highscore. One can leave the app when the game is over.
And here is how it looks in action:
![snake_game_in_action](https://user-images.githubusercontent.com/37499965/94931183-bcf35a00-04c7-11eb-8f2b-a16f28d37399.png)

2020-10-07 19:13 UTC, daniel-thompson commented on wasp/apps/snake.py
> +# 2-bit RLE, generated from res/snake_game.png, 856 bytes
As with previous PR, we need res/snake_game.png to be included as well as the resulting RLE code.

2020-10-07 19:14 UTC, daniel-thompson commented on wasp/apps/snake.py
> +        self.foodLocation()
snake_case_please ;-)

2020-10-07 19:15 UTC, daniel-thompson commented on wasp/apps/snake.py
> +        pass
I think this function is redundant and can be removed.

2020-10-07 19:23 UTC, daniel-thompson commented on wasp/apps/snake.py
> +        pass
Again... no need to implement the sleep/wake callbacks.

2020-10-07 19:25 UTC, daniel-thompson commented on wasp/apps/snake.py
> +        wasp.watch.drawable.fill()
If you have a _draw() method why put the fill here?

2020-10-07 19:26 UTC, daniel-thompson commented on wasp/apps/snake.py
> +            print("Error!")
Remove debugging code.

2020-10-07 19:30 UTC, daniel-thompson commented on wasp/apps/snake.py
> +        wasp.system.switch(LauncherApp())
No need to open code this. If you want to allow the swipe to work "as normal" when the game isn't running just `return True` from the swipe() funciton and the event will be passed to the system event handling.

2020-10-07 19:30 UTC, daniel-thompson commented on wasp/apps/snake.py
> +    def foodLocation(self):
snake_case_please

2020-10-07 19:35 UTC, daniel-thompson commented on wasp/apps/snake.py
> +    def setDir(self,x,y):
snake_case

2020-10-07 19:35 UTC, daniel-thompson commented on wasp/apps/snake.py
> +    def endGame(self):
snake_case

2020-10-07 19:37 UTC, daniel-thompson commented on wasp/wasp.py
> +                         (SnakeGameApp, False),
As before, let's leave this for users to add to main.py .

2020-10-07 19:40 UTC, daniel-thompson requested changes
Mostly fussy details in this review. I haven't tested as yet but I will keep your comment about draw problem during eating in mind.

BTW I also realized there's no docstrings in these apps and they are not integrated into the manual. I'd like to get the extra bonus apps (like Game of Life and your Snake game) into the docs and with screenshots. That will help people find them. It's fine to put it alongside other apps at the moment although I will probably move the optional apps into a user manual instead eventually.

2020-10-07 19:45 UTC, daniel-thompson commented
What's the authorship of this code? I can see some of the code has come from another contributor but there's no Signed-off-by from the author. Is @wbjeffrey ok for this to be submitted (and able to provide a Signed-off-by: ).

2020-10-07 19:54 UTC, wbjeffrey commented
@daniel-thompson  I'm not sure why I've been mentioned on this pull request. I don't have anything to do with this.

2020-10-07 19:57 UTC, daniel-thompson commented
Ah... because I added this into the wrong PR... it should be in #74 where you are listed as the author of two the fibonaci clock patches.

2020-10-07 20:06 UTC, wbjeffrey commented
@daniel-thompson That is really, really weird because I have nothing to do with that either. I don't know how my name is attached to that. I've not done anything other than the flash wake/sleep stuff.

2020-10-16 09:18 UTC, tht-jxny commented
Regarding authorship: During my first commit in this branch, @wbjeffrey also caught my eye as an author. But I didn't care about it because I thought it wasn't that important.

2020-10-16 09:21 UTC, tht-jxny commented
I could create a manual for the applications I created. @daniel-thompson . could you please start with the manual for your Game of Life application so I know what content is expected?

2020-11-08 16:22 UTC, daniel-thompson commented
> I could create a manual for the applications I created. @daniel-thompson . could you please start with the manual for your Game of Life application so I know what content is expected?

Both the fibonacci clock and game of life are now included in the [application library](https://wasp-os.readthedocs.io/en/latest/apps.html) in the documentation. In both cases all that has been done is a simulator screenshot has been dropped into the res/ directory (play the game until the screen looks interesting, then press 's'), there has been markup text describing the app added at the top of the file and the app has been listed in doc/apps.rst .

2020-11-22 09:43 UTC, tht-jxny commented
> > I could create a manual for the applications I created. @daniel-thompson . could you please start with the manual for your Game of Life application so I know what content is expected?
> 
> Both the fibonacci clock and game of life are now included in the [application library](https://wasp-os.readthedocs.io/en/latest/apps.html) in the documentation. In both cases all that has been done is a simulator screenshot has been dropped into the res/ directory (play the game until the screen looks interesting, then press 's'), there has been markup text describing the app added at the top of the file and the app has been listed in doc/apps.rst .

I'd really like to work on this but unfortunately, my fork is too far behind the current commit, so some files like `docs/apps.rst` are not yet available. This makes it difficult for me to make the desired changes, considering t that I'm actually a beginner when it comes to Git. Could you please give me some advice on how to address this problem?

2020-11-26 21:03 UTC, daniel-thompson commented
> Could you please give me some advice on how to address this problem?

I would:

* Use `git branch` to make a back up of where you currently are in a seperate branch
* Use `get fetch origin` to get the latest code onto you rmachine (but not do anything with it)
* Use `git rebase origin/master` to replay your patches on top if the latest code... this is the bit where you need to pay attention because you may have to resolve merge conflicts. If you get conflicts read the prompts on-screen and take it slow. It basically means editing the conflicting file and looking for chevrons (`>>>>>>` or `<<<<<<` and editing that bit until it looks right again...  then continuing the rebase (you should only get conflicts on code you have previously edited so making it "look right again" isn't as hard as it sounds). If you do get stuck hopefully you can find a good blog post or video specifically about rebasing.
* Make some further changes, test, etc, etc, etc.
* Commit the changes as usual and then push them with `--force` flag in order to update the PR

So the two tricks are `git rebase` (which is tricky) and using `--force` on the git push when you're done (which is easy now you know about it but hard to figure out on your own).

This is also drilling some very useful git techniques! I'm a very heavy user of interactive rebases (`git rebase -i origin/master`) to update, edit and imporve the patches I have in my git repo before I push them. Interactive rebasing it a really good way to edit a pull request before force pushing an updated version.

2020-11-27 10:43 UTC, tht-jxny commented
I hope everything works now. Thanks for your help @daniel-thompson. I also followed [this page](https://ardalis.com/syncing-a-fork-of-a-github-repository-with-upstream/).

2020-11-29 20:10 UTC, daniel-thompson commented
Merged! Thanks.

2020-11-29 20:10 UTC, closed without merging